# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da798f3bac2d058d0a7f79f992cb5c5ebd71c170dcd4a3ca881d1e0eb04cde1d4c39badd5db68f7238c960f91abcb883a606001ce3d376de35f0929827e5db5c

test:
  secret_key_base: 03182d9fbae26c7b2ad3583eb6e8c0ee716fc800247840c15b47e802d2103f76fdeb24d27a010c769eacb85b679e4733697698645251db314a77d6c9376d5bb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
